### ISSUE TITLE
Car does not drive

### ISSUE THREAD

**Issue by masskro0** [TrackerSB/DriveBuild#1]
Hello,

I installed DriveBuild according to the installation instructions. I can run DriveBuild without any errors and my created XML files have the right format, since a colleague of mine tested it and they work for him. The problem is that my car can neither drive in manual mode nor in _BEAMNG mode. My car spawns in the middle of the road and the waypoints are set right with enough tolerance. The ego car just stands in his spawn location and nothing happens. The moose test example doesn't work either, I have the same problem there. Neither mainapp nor simnode throw any errors. What could be the cause?

**Comment by alessiogambi** [comment]
Hi,

the fact the same tests work on your colleague's PC might suggests some misconfiguration on your side. It would be helpful if you can gather the following informations (from your PC and possibly the one of your colleague):
- OS
- BeamNG_unlimited SVN revision
- Python Version

Additionally, could you try to launch BeamNG_unlimited (with `-console` option) from command line and manually load the scenario generated using DriveBuild to see if the AI output some message?

Also checking the BeamNG.logs might reveal some error there.

**Comment by masskro0** [comment]
Hello,

my specs are:

- Windows 10 64 Bit
- Latest SVN revision (#14)
- Python version 3.7.0

BeamNG console outputs following errors:
`009.521|E|libbeamng.lua.V|*** FATAL LUA ERROR: [string "string"]:1: unfinished string near '<eof>'
009.522|E|libbeamng.lua.V|*** while executing this line: ai.driveUsingPath({script = {{["pos"]=vec3(7.93695,2.61595,0),["radius"]=0,["radiusOrig"]=0},{["pos"]=vec3(15.9155,11.857,0),["radius"]=0,["radiusOrig"]=0},{["pos"]=vec3(56,3,0),["radius"]=0,["radiusOrig"]=0}}"})
009.523|E|libbeamng.lua.V|*** in chunk: string
009.525|E|BEAMNGCEF::BNGCefClient::OnResourceResponse|MainGEUI | local://local/ui/modules/apps/CharacterRealtimeDisplay/app.js | response: 404 - ERROR`

When I manually load the scenario, I can drive manually around and the beamng intern AI follows the waypoints as well.

Checking the logs reveals:
`8.52655|E|GameEngineLua|*** FATAL LUA ERROR: [string "lua/ge/extensions//scenario/waypoints.lua"]:571: attempt to index field 'vehicleWaypointsData' (a nil value)
8.52981|E|GameEngineLua|*** while executing this line: local sh = require('ge/extensions/scenario/scenariohelper')
local function onWaypoint(data)
  if data['event'] == 'enter' then
    local modeFile = io.open('ego_movementMode', 'w')
    modeFile:write('_BEAMNG')
    modeFile:close()
    sh.setAiPath({vehicleName='ego', waypoints={'wp_ego_1', 'wp_ego_2', 'wp_ego_3'}, driveInLane='on'})
  end
end`

Thanks for the help!

**Comment by alessiogambi** [comment]
I am not sure, did this solve your problem? 

Installing DriveBuild also requires to patch a lua file inside BeamNG_unlimited, maybe that is what is missing here?

**Comment by masskro0** [comment]
Sadly not.

The patch was listed in the instructions.

I try to make a workaround by converting the xml files to prefab and json files by starting DriveBuild and immediately close it, and after that I'm running it in local mode. This isn't useful to test autonomous cars, but at least I can collect data and calculate my fitness function.

**Comment by alessiogambi** [comment]
Ok. Maybe @TrackerSB can shed some light on this.

**Comment by TrackerSB** [comment]
Could you attach the generated LUA file?

**Comment by TrackerSB** [comment]
Concerning _BEAMNG mode: This special mode has limitations in the definition of waypoints due to the internal implementation of BeamNG. Could you send that to me as well?

**Comment by masskro0** [comment]
This is the issue: When I load a scenario, BeamNG tries to load the id 'ego_vehicle' of the participant in the prefab file. The id of the participant is however 'ego'. I load the right scenario since the map looks as expected. This results in a connection timeout in the vehicle server.

This is the LUA file: https://pastebin.com/SvzykXFg
This is the Prefab file: https://pastebin.com/cLiNBcBG

Thank you so much for helping!

**Comment by TrackerSB** [comment]
Could you show me your generated XML files (DBE and DBC) as well?

**Comment by masskro0** [comment]
https://pastebin.com/uQ10pGFU DBC File
https://pastebin.com/0xGXckUZ DBE File

**Comment by masskro0** [comment]
I could solve the problem with the different ids, but still, my ego car doesn't move in DriveBuild. Mainapp doesn't throw any errors and the only error in SimNode is that it can't create lane markings due to multi-part geometries.

**Comment by TrackerSB** [comment]
Errors araising from problems with lane markings do not affect the behavior of the cars. It just does not show (all) lane markings.

**Comment by TrackerSB** [comment]
After finishing my master thesis multiple parts of my system broke... GPU, Windows, Linux, Python, WLAN connection (due to broken repeater),... The only thing still working is my laptop apart from the fact that occasionally the display turns partially to black... So I may need one or two days to fix the crap and setup DriveBuild properly again. I'm sorry.
I wanted to migrate to Arch anyway...

**Comment by masskro0** [comment]
No problem, you dont have to put so much effort to solve my issue. I can already run the generated tests locally and can even run our own AI. It must be some sort of configuration bug, even though I followed exactly the instructions...

**Comment by TrackerSB** [comment]
If you are able to describe the solution in detail I may include it in the instructions.

**Comment by masskro0** [comment]
This isn't a solution to fix the mentioned issue, but here is what I do:

1. Create (if there isn't) a new drivebuild directory in the levels directory of BeamNG trunk directory.
2. Copy everything that is in DriveBuild's repo under levels -> drivebuild to that created directory.
3. Create a new directory called scenarios under %BeamNG%\trunk\levels\drivebuild (The same directory which was created in the first step and where you copied the files in the second step).
4. Generate both the environment and criteria xml files
5. Run the generated test in DriveBuild
6. Kill the BeamNG process
7. Head over to the BeamNg directory in the documents directory where DriveBuild stores directories with the scenarios. (drivebuild_xx)
8. Pick the newest created directory
9. Go to levels -> drivebuild -> scenarios and copy all files (json, lua and prefab)
10. Paste them in the scenarios directory of step 3
11. Now you can start BeamNG as you normally would. For example, my scenario looks like this:
`scenario = Scenario('drivebuild', 'drivebuild_77)
destination_path = 'D:\\Program Files (x86)\\BeamNG\\levels\\drivebuild\\scenarios'
scenario.path = Path(destination_path)`
Adjust the destination_path to the path of step 3.
I wrote a Python script to automatically execute the steps 4-11.

**Comment by TrackerSB** [comment]
Did you create the junction in the levels folder as in the instructions?

**Comment by masskro0** [comment]
When I did it the first time, I got the error that this file already exists.

**Comment by TrackerSB** [comment]
I executed your test as it is. I did not encounter any problem apart from the missing lane markings which may be a feature for future versions.

**Comment by masskro0** [comment]
I'm not sure if it's related with the above mentioned issue, but by debugging I could find out that the method `wait_for_simulator_request` in the class `AIExchangeService` is not coming further than the line
`response = do_get_request(self.host, self.port, "/ai/waitForSimulatorRequest", {
            "sid": sid.SerializeToString(),
            "vid": vid.SerializeToString()
        })`

Could this be the issue here? The documentation states: 

`This call blocks until the simulation requests the appropriate car in the given simulation.`

And since I can't create a GET request, the simulator just blocks any interaction.

Thank you a lot in advance!

**Comment by TrackerSB** [comment]
Per design the call blocks until the simulation instance that results from your submitted test is up and starts executing the test.

**Comment by masskro0** [comment]
After months, I found out that the car doesn't move because of the sh.setAiPath function in Lua. I tried this function local and the car didn't drive.  There are no error messages. I try to find out why this is happening.

**Comment by TrackerSB** [comment]
That's very interesting. Do you use the most recent revision of BeamNG?

**Comment by TrackerSB** [comment]
If it is a bug BeamNG might be interested about that.

**Comment by masskro0** [comment]
I'm using revision 14 (most recent revision when I opened this issue) with BeamNGpy 1.15. We have to include setAiLine in scenariohelper.lua but when is this function called? Instead, setAiPath is called. I will post when I know more about this issue.

**Comment by TrackerSB** [comment]
The function is called in `/simnode/sim_controller.py` in line 125. The function `_generate_lua_av_command` generates LUA commands that are placed e.g. in prefab files. It is quite hard to see what's going on there due to all the string concatination.
