### ISSUE TITLE
Problems connecting to the psql database

### ISSUE THREAD

**Issue by timbleman** [TrackerSB/DriveBuild#2]
Hello,

I have problems running DriveBuild on my main computer. I have installed PostgreSQL multiple times now and configured it and app.cf and config.py multiple times now, however as soon as i run the example start.py I get the error "Running tests errored: Login or password incorrect.".  The psql database is the same as on my laptop, username and password are both 'test'. I also looked at the place in the code where the error is thrown (AIExchangeService.py) and printed out the password and username, both are test aswell. Encoding is set to UTF-8.

**Comment by alessiogambi** [comment]
Hi, can you connect to the drivebuild database in PostgresSQL using the PostgresSQL console?

Just a wild guess: Can you double check that there are no spaces or other weird characters?

**Comment by timbleman** [comment]
I can connect using the psql console. I used the exact commands for the github readme and the entries look exactly like on my laptop.

**Comment by alessiogambi** [comment]
Ok. Can you try to create a completely new DriveBuild user, with different credentials, and see if the problem persists? Of course, update your python code to use the new user instead of the old one.

**Comment by timbleman** [comment]
Okay, I have created a new user and database with a different name exactly the same way as before and it seems to work now. Thank you very much!

**Comment by alessiogambi** [comment]
I am curios why the it failed with the other user, nevertheless, since this if fixed I close the issue.
