### ISSUE TITLE
Problems running DriveBuild on my laptop

### ISSUE THREAD

**Issue by timbleman** [TrackerSB/DriveBuild#3]
Hello,

I have installed DriveBuild on my laptop and can run xml files, roads and waypoints are correctly displayed. However, as soon as i attach a camera to the vehicle BeamNG crashes after just a few seconds. I could imagine, that this is not an issue of DriveBuild, but BeamNG, there is a separate branch for my Intel HD 620 GPU for the regular Steam version.

**Comment by alessiogambi** [comment]
Hi,

could you check if you experience the same problem by running BeamNG directly with BeamNGpy?
Could you check if you experience the same problem if you *manually* run BeamNG and a scenario, and then use BeamNGpy to attach to it?
Does it happens with basic camera, with pixel annotated images, or both?

**Comment by timbleman** [comment]
The crashes also appear in BeamNGpy directly. It happens with many different camera settings, the lidar sensor also causes crashes. It runs very poorly in general and crashes randomly after some time, even when only driving manualy, so i will no longer try it on my laptop. Thanks for your help.

**Comment by alessiogambi** [comment]
Sorry to hear that. I had open an issue  about this on BeamNG.research anyways.
I close this as WONTFIX
